### ISSUE TITLE
File select dialog shows up again right after I select a file.

### ISSUE THREAD

**Issue by arkadiyk** [captivationsoftware/react-file-input#2]
Selecting file again, when it pops up the second time seems to be working.
The same issue is on the demo page.
OSX, Chrome Version 44.0.2403.61 beta (64-bit)

**Comment by brianblocker** [comment]
:+1: experiencing the same on the demo

**Comment by captivationsoftware** [comment]
@brianblocker Are you also on OSX? I'm not seeing the issue on FF or Chrome on Linux

**Comment by brianblocker** [comment]
Yes. I didn't dive in to the code to try and diagnose, but I will

**Comment by kinergy** [comment]
Seeing it too on Chrome (43.0.2357.132 (64-bit)) on OS X 10.10.4.
Firefox and Safari are fine.

**Comment by danielmeneses** [comment]
Same here!!!

**Comment by captivationsoftware** [comment]
Fixed in 0.2.1
