### ISSUE TITLE
Synthetic event properties null

### ISSUE THREAD

**Issue by rubencodes** [captivationsoftware/react-file-input#3]
Hello,

I tried using your plugin and found that the file received by the event handler was a Synthetic event with all its properties set to null. Is a fix in the works? I tried the demo and noticed the same thing happens. Thanks!

**Comment by captivationsoftware** [comment]
OK, I suspect this is a documentation issue and not a code problem. A file isn't passed to the onChange callback as the docs suggest -- only the event.  Through the event, you can can get the target and eventually just say something like, "event.target.files[0]" to extract the file from the event.

I'm not opposed to passing the file as a second argument to the callback, too. However,  I don't see this as necessary. A PR to do so would likely be merged in though, hint hint...

Anyway, I updated the documentation -- try again after giving it a read and let me know if you're still having problems. 

Thanks!

**Comment by rubencodes** [comment]
I _just_ figured that out. My bad! Thanks!

**Comment by captivationsoftware** [comment]
It's cool! Thanks for helping make the project better!
