### ISSUE TITLE
How to select the same file twice in a row?

### ISSUE THREAD

**Issue by alexklibisz** [captivationsoftware/react-file-input#5]
First, thank you for making this, it's a very helpful tool.

I'm trying to handle the case where a user:
- selects a file, say "abc.txt"
- does some other things in the app
- selects the same file, "abc.txt"

The second time the same file is selected, the onChange() handler does not fire. This does make sense, because the file technically has not changed. 

But is there any way to "reset" the input, so that the same file will trigger some sort of event that I can handle?

I have setting a ref: `<FileInput ref="myFile" ... />` followed by calling `this.refs.myFile.state.value = '';` in the `onChange` function. This clears the string value in the input field, but it does not "reset" the component.

**Comment by silversoup** [comment]
I had the same issue, and decided I'd just completely re-render the component before selecting the same file again. As the underlying input component does not recognize the file has changed, this might be the best we can do with this. 
Here's how I'm doing the reset
http://stackoverflow.com/questions/21749798/how-can-i-reset-a-react-component-including-all-transitively-reachable-state

**Comment by alexklibisz** [comment]
@silversoup 

Thanks! I got it to work by calling:

```
this.refs.myFile.replaceState(this.refs.myFile.getInitialState());
```

A little wordy but works.
